/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RegisteredDiaryIndexState {
  diaryName: string
  generation: number
  contentRevision: number
  dimension: number
  totalVectors: number
}
export interface NativeKnowledgeRuntimeStats {
  acceptingQueries: boolean
  dimension: number
  registeredDiaries: number
  registryGeneration: number
  memoRuntimeResident: boolean
  memoArtifactSig?: string
  memoGeneration: number
}
export interface NativeMemoArtifactBuildResult {
  success: boolean
  artifactSig: string
  sourceArtifactSig: string
  graphGeneration: string
  databaseGeneration: string
  provenanceGeneration: string
  generation: number
  nodeCount: number
  edgeCount: number
  persisted: boolean
  resident: boolean
  elapsedMs: number
}
/**
 * 统一 Memo 查询的轻量 N-API 返回值。
 *
 * 完整 Observation、双场、域集合与投影向量只保留在 MemoRuntime 中；Node
 * 只接收后续读出所需的句柄、诊断摘要和用于 KNN 的增强查询向量。
 */
export interface MemoPipelineResult {
  metadataJson: string
  enhancedVector: Float32Array
}
/**
 * 搜索结果 (返回 ID 而非 Tag 文本)
 * 上层 JS 会拿着 ID 去 SQLite 里查具体的文本内容
 */
export interface SearchResult {
  id: number
  score: number
}
export interface SvdResult {
  u: Array<number>
  s: Array<number>
  k: number
  dim: number
}
export interface OrthogonalProjectionResult {
  projection: Array<number>
  residual: Array<number>
  basisCoefficients: Array<number>
}
export interface HandshakeResult {
  magnitudes: Array<number>
  directions: Array<number>
}
export interface ProjectResult {
  projections: Array<number>
  probabilities: Array<number>
  entropy: number
  totalEnergy: number
}
export interface DualWeightedProjectionResult {
  localVector?: Array<number>
  transferVector?: Array<number>
  requestedCount: number
  foundCount: number
  missingCount: number
  localTotalWeight: number
  transferTotalWeight: number
  elapsedMs: number
}
export interface MemoFusionResult {
  vector: Array<number>
  selectedTagIds: Array<number>
  requestedCount: number
  foundCount: number
  deduplicatedCount: number
  totalWeight: number
  elapsedMs: number
}
export interface IntrinsicResidualResult {
  tagCount: number
  computedCount: number
  skippedCount: number
  elapsedMs: number
  algorithmVersion: string
  artifactSig: string
  effectiveConfig: string
}
/** 🌟 EPA Rust 基底重算结果 */
export interface EpaBasisResult {
  success: boolean
  message: string
  tagCount: number
  clusterCount: number
  basisCount: number
  elapsedMs: number
  algorithm: string
  phaseSummary: string
  anchorCount: number
  representativeSampleCount: number
  densityBucketCount: number
  publishElapsedMs: number
}
/** 🌟 TagMemo V8.2: 成对语义距离预计算结果 */
export interface PairwiseSimResult {
  pairCount: number
  computedCount: number
  skippedCount: number
  storedCount: number
  elapsedMs: number
}
/** 统计信息 */
export interface VexusStats {
  totalVectors: number
  dimensions: number
  capacity: number
  memoryUsage: number
}
/** 对任意 Chunk/日记索引执行单次排他差分后的摘要。  */
export interface ChunkIndexDeltaResult {
  requestedDeletes: number
  requestedUpserts: number
  appliedDeletes: number
  appliedUpserts: number
  totalVectors: number
  previousRevision: number
  revision: number
}
/** 对活动 Tag 索引执行单次排他差分后的摘要。 */
export interface TagIndexDeltaResult {
  requestedDeletes: number
  requestedUpserts: number
  appliedDeletes: number
  appliedUpserts: number
  totalVectors: number
  memoRuntimeCleared: boolean
}
/** VexusIndex 内部统一 Memo 运行时诊断。 */
export interface MemoRuntimeStats {
  activeArtifactSig?: string
  generation: number
  nodeCount: number
  edgeCount: number
  resident: boolean
}
export interface WatcherConfig {
  rootPath: string
  ignoreFolders: Array<string>
  ignorePrefixes: Array<string>
  ignoreSuffixes: Array<string>
  /** 可选扩展名白名单。为空时保持旧行为：仅监听 .md / .txt。 */
  extensions?: Array<string>
  /** 路径事件静默窗口。窗口内的新事件会使旧 generation 自动失效。 */
  debounceMs?: number
  /** 两次文件元数据采样之间的稳定确认间隔。 */
  stabilityMs?: number
  /** 同一 generation 内最多执行的稳定采样次数。 */
  stabilityRetries?: number
}
export declare class NativeKnowledgeRuntime {
  /**
   * 创建实例级知识查询运行时，并绑定全局 Tag VexusIndex 拥有的 MemoRuntime。
   *
   * 构造完成后只持有纯 Rust Arc，不保存 N-API 对象引用。
   */
  constructor(tagIndex: VexusIndex)
  /**
   * 注册或原子替换一个日记索引。
   *
   * 返回由 Runtime 自身分配的 generation；后续注销必须携带该 generation，
   * 防止旧的空闲淘汰任务误删同名新实例。
   */
  registerDiaryIndex(diaryName: string, diaryIndex: VexusIndex): RegisteredDiaryIndexState
  /** 在多个已注册日记索引上执行一次后台 ANN，并按 Chunk ID 确定性合并。 */
  searchDiaryIndices(diaryNames: Array<string>, query: Float32Array, perIndexK: number, globalK: number): Promise<unknown>
  /**
   * 多索引 ANN 后在同一后台任务中批量读取 Chunk 向量并执行确定性语义去重。
   *
   * global_k 是进入语义阶段的候选池上限；final_k 是去重后的输出上限。
   * final_k 省略时回退 global_k，保持早期 ABI 调用兼容。
   */
  searchDiaryIndicesDeduplicated(dbPath: string, diaryNames: Array<string>, query: Float32Array, perIndexK: number, globalK: number, semanticThreshold: number, finalK?: number | undefined | null): Promise<unknown>
  /**
   * 使用已有 Memo observationHandle，在一次 N-API 后台任务中执行：
   * 多索引 ANN → Chunk ID 合并 → SQLite 批量向量 hydrate → 语义去重
   * → RiverMemo Topology V3。river_input_json 中的 candidates 会被忽略并由
   * 原生检索结果替换；topK、权限作用域和 Topology 配置保持原契约。
   */
  executeRiverQuery(dbPath: string, artifactSig: string, riverInputJson: string, diaryNames: Array<string>, query: Float32Array, perIndexK: number, candidateK: number, semanticThreshold: number): Promise<unknown>
  /**
   * Native Query Plan V2：在一次后台任务中融合当前向量、历史分段向量、
   * Time 文件候选和 BM25 文件候选，再执行统一语义去重与 Topology V3。
   *
   * supplemental_vectors 是 count × dimension 的扁平 Float32Array；低维计划
   * 继续使用 JSON，避免任何 Chunk/Tag 高维向量经 JSON 或 N-API 往返。
   */
  executeRiverQueryHybrid(dbPath: string, artifactSig: string, riverInputJson: string, diaryNames: Array<string>, query: Float32Array, supplementalVectors: Float32Array, hybridPlanJson: string, perIndexK: number, candidateK: number, semanticThreshold: number): Promise<unknown>
  /** 按 expectedGeneration 注销索引。代际不匹配时返回 false，不修改注册表。 */
  unregisterDiaryIndex(diaryName: string, expectedGeneration: number): boolean
  diaryIndexState(diaryName: string): RegisteredDiaryIndexState | null
  listDiaryIndices(): Array<RegisteredDiaryIndexState>
  stats(): NativeKnowledgeRuntimeStats
  /** 停止接受后续查询并清空注册表。已开始任务持有的 Arc 快照不受影响。 */
  shutdown(): void
}
/** 核心索引结构 (无状态，只存向量) */
export declare class VexusIndex {
  /** 创建新的空索引 */
  constructor(dim: number, capacity: number)
  /**
   * 从磁盘加载索引
   * 注意：移除了 map_path，因为映射关系现在由 SQLite 管理
   */
  static load(indexPath: string, unusedMapPath: string | undefined | null, dim: number, capacity: number): VexusIndex
  /**
   * 保存索引到磁盘。
   *
   * 临时文件始终与目标位于同一目录，保证 rename 不跨文件系统。Unix 使用
   * 原子覆盖并同步父目录；Windows 使用可回滚备份交换，并对杀毒软件、索引器
   * 短暂持有句柄造成的共享冲突进行有界重试。
   */
  save(indexPath: string): void
  /** 单个添加 (JS 循环调用) */
  add(id: number, vector: Float32Array): void
  /**
   * 批量添加 (FFI 优化版)
   * 注意：这目前是一个“伪批量”实现，主要通过减少 JS/Rust 跨界调用开销来提速。
   * 内部依然是逐条 add，但避免了多次获取写锁的开销。
   */
  addBatch(ids: Array<number>, vectors: Float32Array): void
  /**
   * 对日记/Chunk 索引执行一次后台排他差分。
   *
   * 删除、容量预留和全部 upsert 在同一写锁内完成。并发 search 只能在整个
   * 批次之前或之后取得读锁，不会观察到公共索引的半批状态。
   */
  applyChunkDelta(removeIds: Array<number>, upsertIds: Array<number>, upsertVectors: Float32Array): Promise<unknown>
  /** 返回当前索引内容代际。 */
  get revision(): number
  /**
   * 对当前活动 Tag 索引执行一次后台排他差分。
   *
   * N-API 调用只复制实际变化的向量并立即返回 Promise；耗时的 usearch 删除、
   * upsert 与 MemoRuntime 失效均在 libuv 工作线程执行，不阻塞 Node 事件循环。
   * 搜索通过同一 RwLock 等待差分完成，只会看到差分前或差分后的索引。
   */
  applyTagDelta(removeIds: Array<number>, upsertIds: Array<number>, upsertVectors: Float32Array): Promise<unknown>
  /** 搜索 */
  search(query: Float32Array, k: number): Array<SearchResult>
  /**
   * RiverMemo 全局双场投影。
   *
   * Tag 向量直接从当前常驻 usearch F32 索引按 key 读取；整个查询只复用一个
   * dimension 大小的临时缓冲区，不维护第二份全库向量矩阵。
   */
  projectDualWeighted(tagIds: Array<number>, localMasses: Float64Array, transferMasses: Float64Array): DualWeightedProjectionResult
  /**
   * 使用当前 VexusIndex 唯一 Tag 向量空间完成 TagMemo 上下文融合。
   *
   * 只在批量读取请求涉及的 Tag 向量时短持 usearch 读锁；语义去重、
   * 上下文加权和最终融合均在释放索引锁后执行，不维护第二份全库向量。
   */
  fuseMemoContext(original: Float32Array, tagIds: Array<number>, tagWeights: Float64Array, alpha: number, dedupThreshold?: number | undefined | null, maxTags?: number | undefined | null): MemoFusionResult
  /**
   * 在本 Tag 向量索引与 MemoRuntime 上执行统一查询数学管线。
   *
   * EPA、Residual Pyramid、Core/语言/层级门控、Spike 与向量融合全部在
   * 同一 Rust 后台任务中完成；返回值同时供 DTSC 和 Topology V3 读出复用。
   */
  runMemoPipeline(dbPath: string, artifactSig: string, inputJson: string, queryVector: Float32Array, ghostVectors: Float32Array): Promise<unknown>
  /**
   * 在统一 QueryObservation 上执行 DTSC 测地曲线读出。
   *
   * 与 RiverMemo Topology V3 读取同一个 MemoRuntime 活动图快照；
   * 差异只存在于读出方程，不再拥有独立图资产。
   */
  rerankMemoDtsc(dbPath: string, artifactSig: string, inputJson: string): Promise<unknown>
  /**
   * 在本 Tag 向量索引拥有的统一 MemoRuntime 上执行 RiverMemo Topology V3。
   *
   * 首次请求从持久化资产恢复 CSR，随后由本 VexusIndex 实例持有活动 Arc 快照；
   * 查询只克隆快照，不再访问进程全局生产缓存。
   */
  rerankRivermemoTopologyV3(dbPath: string, artifactSig: string, inputJson: string): Promise<unknown>
  /**
   * 从 SQLite 事实层和 Rust 派生表原生编译统一 Memo 图资产。
   *
   * 完整图、CSR、provenance、持久化 payload 与活动 Arc 均不跨越
   * N-API 边界；JavaScript 只接收签名、代际与规模摘要。
   */
  rebuildMemoArtifact(dbPath: string, inputJson: string): Promise<unknown>
  /** 释放本索引持有的统一 Memo 图快照。 */
  clearMemoRuntime(): void
  /** 获取统一 Memo 图快照的常驻诊断。 */
  memoRuntimeStats(): MemoRuntimeStats
  /** 删除 (按 ID) */
  remove(id: number): void
  /** 获取当前索引状态 */
  stats(): VexusStats
  /** 从 SQLite 数据库恢复索引 (异步版本，不阻塞主线程) */
  recoverFromSqlite(dbPath: string, tableType: string, filterDiaryName?: string | undefined | null): Promise<unknown>
  /**
   * 高性能 SVD 分解 (用于 EPA 基底构建)
   * flattened_vectors: n * dim 的扁平化向量数组
   * n: 向量数量
   * max_k: 最大保留的主成分数量
   */
  computeSvd(flattenedVectors: Float32Array, n: number, maxK: number): SvdResult
  /** 高性能 Gram-Schmidt 正交投影 */
  computeOrthogonalProjection(vector: Float32Array, flattenedTags: Float32Array, nTags: number): OrthogonalProjectionResult
  /** 高性能握手分析 */
  computeHandshakes(query: Float32Array, flattenedTags: Float32Array, nTags: number): HandshakeResult
  /** 高性能 EPA 投影 */
  project(vector: Float32Array, flattenedBasis: Float32Array, meanVector: Float32Array, k: number): ProjectResult
  /**
   * 🌟 EPA: Rust 侧重算基底并暂存在 Rust 内存中。
   *
   * 计算阶段只读 SQLite，不持有 JS 写租约；调用方应在结果成功后短租约调用 publish_epa_basis_cache。
   */
  computeEpaBasis(dbPath: string, clusterCount: number, maxBasisDim: number): Promise<unknown>
  /**
   * 🌟 EPA: 发布最近一次 Rust 计算完成的 EPA cache。
   *
   * 该方法执行短 SQLite 写入，JS 调用方必须先获取 Rust 写租约。
   */
  publishEpaBasisCache(dbPath: string): EpaBasisResult
  /** 预计算任务：矩阵内生残差 (TagMemo V7) */
  computeIntrinsicResiduals(dbPath: string, maxSvdRank?: number | undefined | null, minNeighbors?: number | undefined | null, modelSig?: string | undefined | null, effectiveConfigJson?: string | undefined | null): Promise<unknown>
  /**
   * 🌟 TagMemo V8.2: 预计算 Tag 对的语义距离（成对余弦相似度）
   *
   * - 仅对实际共现的 pair 进行计算（避免 N² 爆炸）
   * - 单文件 Tag 数 > 100 的脏文件跳过（与 JS / V7 守恒一致）
   * - 增量模式：已存在且 model_sig 一致的 pair 直接跳过
   * - sim < min_similarity 的 pair 不写入（默认丢弃噪声）
   * - 单模型缓存策略：full_rebuild 会清空整张 sim 表，避免旧模型签名残留
   *
   * # 参数
   * - `db_path`: SQLite 路径
   * - `model_sig`: embedding 模型签名 (含维度)，跨模型自动失效
   * - `min_similarity`: 噪声阈值，默认 0.05
   * - `full_rebuild`: 是否清空 sim 表后重算 (默认 false 增量)
   */
  computePairwiseSimilarities(dbPath: string, modelSig: string, minSimilarity?: number | undefined | null, fullRebuild?: boolean | undefined | null): Promise<unknown>
}
export declare class VexusWatcher {
  constructor()
  /** 启动高性能原生文件监听 */
  startWatch(config: WatcherConfig, jsCallback: (err: Error | null, arg: string) => any): void
  /** 停止监听 */
  stopWatch(): void
}
